### ISSUE TITLE
Syncthing v0.11.0

### ISSUE THREAD

**Issue by strayer** [bor/gentoo-overlay#1]
Syncthing v0.11.0 was released yesterday:
https://forum.syncthing.net/t/syncthing-v0-11-0-release-notes/2426

I simply copied the ebuild of v0.10.30 and it seems like everything is still working, so this issue is just a little heads up to let you know :)

**Comment by bor** [comment]
thanks :)
I've just wating
 1) for the stability of new branch
 2) for android version
at the moment seems like all requires are done
so lets bump
